/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentCard: typeof import('./src/components/AgentCard.vue')['default']
    AgentsDrawer: typeof import('./src/components/AgentsDrawer.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ItemCardHeader: typeof import('./src/components/shared/ItemCardHeader.vue')['default']
    LLMParametersForm: typeof import('./src/components/shared/LLMParametersForm.vue')['default']
    MessageBubble: typeof import('./src/components/MessageBubble.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    ProviderConfigFields: typeof import('./src/components/shared/ProviderConfigFields.vue')['default']
    ResizableDivider: typeof import('./src/components/ResizableDivider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    StepLLMConfig: typeof import('./src/components/setup/StepLLMConfig.vue')['default']
    StepProfileCreate: typeof import('./src/components/setup/StepProfileCreate.vue')['default']
    StepServerConfig: typeof import('./src/components/setup/StepServerConfig.vue')['default']
    StepToolConfig: typeof import('./src/components/setup/StepToolConfig.vue')['default']
    TerminalPanel: typeof import('./src/components/TerminalPanel.vue')['default']
    TerminalSession: typeof import('./src/components/TerminalSession.vue')['default']
    ThinkingIndicator: typeof import('./src/components/ThinkingIndicator.vue')['default']
    ToolArgumentsForm: typeof import('./src/components/shared/ToolArgumentsForm.vue')['default']
    ToolVariablesForm: typeof import('./src/components/shared/ToolVariablesForm.vue')['default']
  }
}
